---
grpcport: 50151
httpport: 8082
tlsfiles:
database: redis
dbaddress: 127.0.0.1:6379
buildenv: intel_e2000
tracer: false
subscribers:
  - name: "lvm"
    priority: 2
    events: ["vrf", "bridge-port"]
  - name: "lgm"
    priority: 1
    events: ["vrf", "svi", "logical-bridge"]
  - name: "frr"
    priority: 3
    events: ["vrf", "svi"]
  - name: "intel-e2000"
    priority: 4
    events: ["vrf", "logical-bridge", "bridge-port", "svi"]
grpc:
  server_addresses:
    - 0.0.0.0
  server_port: 51703
  num_threads: 10
  static_external_macs: []
p4:
  enabled: true
  representors:
    port_mux: "port-mux"
    vrf_mux: "vrf-mux"
    grpc_acc: "host"
    grpc_host: "00:20:00:00:14:48"
    phy0_rep: "port0"
    phy1_rep: "port1"
  config:
    p4infofile: /root/p4files/opi_ln.p4info.txt
    binfile: /root/p4files/opi_ln.pb.bin
linuxfrr:
  enabled: true
  defaultvtep: "vxlan-vtep"
  portmux: "enp0s1f0d5"
  vrfmux: "enp0s1f0d4"
  ipmtu: 2962
netlink:
  enabled: true
  pollinterval: 1
  phyports:
    - name: "enp0s1f0d1"
      vsi: 0
    - name: "enp0s1f0d2"
      vsi: 1
loglevel:
  db: INFO
  grpc: INFO
  linux: INFO
  netlink: INFO
  p4: DEBUG
